# 2. Web Scraping — Historical Wikipedia Snapshot
This notebook uses the exact Wikipedia revision specified in the IBM course, from June 9, 2021.

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
from IPython.display import display

static_url = "https://en.wikipedia.org/w/index.php?title=List_of_Falcon_9_and_Falcon_Heavy_launches&oldid=1027686922"
headers = {"User-Agent": "Mozilla/5.0 (compatible; educational capstone project)"}
response = requests.get(static_url, headers=headers, timeout=30)
print("HTTP status:", response.status_code)
response.raise_for_status()

soup = BeautifulSoup(response.text, "html.parser")
print("Page title:", soup.title)
tables = soup.find_all("table")
print("Tables found:", len(tables))

HTTP status: 200
Page title: <title>List of Falcon 9 and Falcon Heavy launches - Wikipedia</title>
Tables found: 29

In [2]:
# Quick structured extraction of HTML tables for inspection
tables_df = pd.read_html(response.text)
print("Tables parsed:", len(tables_df))
for i, table in enumerate(tables_df[:5]):
    print(f"Table {i}: {table.shape}")
    display(table.head(3))

/tmp/ipykernel_1064/1215116971.py:2: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables_df = pd.read_html(response.text)

Tables parsed: 29
Table 0: (1, 2)

,0,1
0,Rocket configurations 5 10 15 20 25 30 '10 '11...,Launch sites 5 10 15 20 25 30 '10 '11 '12 '13 ...

Table 1: (1, 2)

,0,1
0,Launch outcomes 10 20 30 40 50 '10 '11 '12 '13...,Booster landings 5 10 15 20 25 30 '10 '11 '12 ...

Table 2: (15, 10)

,Flight No.,Date and time (UTC),"Version, Booster [b]",Launch site,Payload[c],Payload mass,Orbit,Customer,Launch outcome,Booster landing
0,1,"4 June 2010, 18:45",F9 v1.0[7] B0003.1[8],"CCAFS, SLC-40",Dragon Spacecraft Qualification Unit,NaN,LEO,SpaceX,Success,Failure[9][10] (parachute)
1,1,First flight of Falcon 9 v1.0.[11] Used a boil...,First flight of Falcon 9 v1.0.[11] Used a boil...,First flight of Falcon 9 v1.0.[11] Used a boil...,First flight of Falcon 9 v1.0.[11] Used a boil...,First flight of Falcon 9 v1.0.[11] Used a boil...,First flight of Falcon 9 v1.0.[11] Used a boil...,First flight of Falcon 9 v1.0.[11] Used a boil...,First flight of Falcon 9 v1.0.[11] Used a boil...,First flight of Falcon 9 v1.0.[11] Used a boil...
2,2,"8 December 2010, 15:43[13]",F9 v1.0[7] B0004.1[8],"CCAFS, SLC-40",Dragon demo flight C1 (Dragon C101),NaN,LEO (ISS),NASA (COTS) NRO,Success[9],Failure[9][14] (parachute)

Table 3: (12, 10)

,Flight No.,Date and time (UTC),"Version, Booster[b]",Launch site,Payload[c],Payload mass,Orbit,Customer,Launch outcome,Booster landing
0,8,"6 January 2014, 22:06[41]",F9 v1.1,"CCAFS, SLC-40",Thaicom 6[22],"3,325 kg (7,330 lb)",GTO,Thaicom,Success[42],No attempt [43]
1,8,The Thai communication satellite was the secon...,The Thai communication satellite was the secon...,The Thai communication satellite was the secon...,The Thai communication satellite was the secon...,The Thai communication satellite was the secon...,The Thai communication satellite was the secon...,The Thai communication satellite was the secon...,The Thai communication satellite was the secon...,The Thai communication satellite was the secon...
2,9,"18 April 2014, 19:25[21]",F9 v1.1,"Cape Canaveral, LC-40",SpaceX CRS-3[22] (Dragon C105),"2,296 kg (5,062 lb)[45]",LEO (ISS),NASA (CRS),Success,Controlled (ocean) [d][46]

Table 4: (14, 10)

,Flight No.,Date and time (UTC),"Version, Booster[b]",Launch site,Payload[c],Payload mass,Orbit,Customer,Launch outcome,Booster landing
0,14,"10 January 2015, 09:47[67]",F9 v1.1 B1012[8],"Cape Canaveral, LC-40",SpaceX CRS-5[68] (Dragon C107),"2,395 kg (5,280 lb)[69]",LEO (ISS),NASA (CRS),Success[70],Failure (drone ship)
1,14,"Following second-stage separation, SpaceX atte...","Following second-stage separation, SpaceX atte...","Following second-stage separation, SpaceX atte...","Following second-stage separation, SpaceX atte...","Following second-stage separation, SpaceX atte...","Following second-stage separation, SpaceX atte...","Following second-stage separation, SpaceX atte...","Following second-stage separation, SpaceX atte...","Following second-stage separation, SpaceX atte..."
2,15,"11 February 2015, 23:03[72]",F9 v1.1 B1013[8],"Cape Canaveral, LC-40",DSCOVR[68][73],"570 kg (1,260 lb)",HEO (Sun–Earth L1 insertion),USAF NASA NOAA,Success,Controlled (ocean)[d]

In [3]:
# Save the table most likely to contain launch history for manual inspection.
# Wikipedia table layouts can change; inspect the displayed tables before choosing.
for i, table in enumerate(tables_df):
    print(i, table.shape, list(table.columns)[:6])

0 (1, 2) [0, 1]
1 (1, 2) [0, 1]
2 (15, 10) ['Flight No.', 'Date and time (UTC)', 'Version, Booster [b]', 'Launch site', 'Payload[c]', 'Payload mass']
3 (12, 10) ['Flight No.', 'Date and time (UTC)', 'Version, Booster[b]', 'Launch site', 'Payload[c]', 'Payload mass']
4 (14, 10) ['Flight No.', 'Date and time (UTC)', 'Version, Booster[b]', 'Launch site', 'Payload[c]', 'Payload mass']
5 (18, 10) ['Flight No.', 'Date and time (UTC)', 'Version, Booster[b]', 'Launch site', 'Payload[c]', 'Payload mass']
6 (36, 10) ['Flight No.', 'Date and time (UTC)', 'Version, Booster[b]', 'Launch site', 'Payload[c]', 'Payload mass']
7 (44, 10) ['Flight No.', 'Date and time (UTC)', 'Version, Booster[b]', 'Launch site', 'Payload[c]', 'Payload mass']
8 (30, 10) ['Flight No.', 'Date and time (UTC)', 'Version, Booster[b]', 'Launch site', 'Payload[c]', 'Payload mass']
9 (53, 10) ['Flight No.', 'Date and time (UTC)', 'Version, Booster[b]', 'Launch site', 'Payload[c]', 'Payload mass']
10 (37, 10) ['Flight No.', 'Date and time (UTC)', 'Version, Booster[b]', 'Launch site', 'Payload[c]', 'Payload mass']
11 (44, 6) ['Date and time (UTC)', 'Version, Booster[b]', 'Launch site', 'Payload[c]', 'Orbit', 'Customer']
12 (65, 6) ['Date and time (UTC)', 'Version, Booster[b]', 'Launch site', 'Payload[c]', 'Orbit', 'Customer']
13 (37, 6) ['Date and time (UTC)', 'Version, Booster[b]', 'Launch site', 'Payload[c]', 'Orbit', 'Customer']
14 (15, 6) ['Date and time (UTC)', 'Version, Booster[b]', 'Launch site', 'Payload[c]', 'Orbit', 'Customer']
15 (20, 2) ['vteSpaceX missions and payloads', 'vteSpaceX missions and payloads.1']
16 (11, 2) [0, 1]
17 (3, 2) [0, 1]
18 (3, 2) [0, 1]
19 (25, 2) ['vteSpaceX', 'vteSpaceX.1']
20 (4, 2) [0, 1]
21 (2, 2) [0, 1]
22 (2, 2) [0, 1]
23 (22, 2) ['vteSpaceflight lists and timelines', 'vteSpaceflight lists and timelines.1']
24 (8, 2) [0, 1]
25 (4, 2) [0, 1]
26 (1, 2) [0, 1]
27 (1, 2) [0, 1]
28 (1, 2) [0, 1]

## Note
The official course lab uses custom parsing logic to normalize launch tables across different table formats. This notebook demonstrates the fixed source and table inspection. Use the course-provided scraped dataset for downstream graded results if your instructor supplied one.