# 3. Data Wrangling
This notebook loads the course-style prepared dataset from a public reference repository so that the later analysis is reproducible. Review the source and cite it in your README; replace the URL with your own course-provided CSV if available.

Reference dataset repository: https://github.com/chuksoo/IBM-Data-Science-Capstone-SpaceX

In [1]:
import pandas as pd
import numpy as np
from IPython.display import display

BASE = "https://raw.githubusercontent.com/chuksoo/IBM-Data-Science-Capstone-SpaceX/main"
url = BASE + "/dataset_part_1.csv"
df = pd.read_csv(url)
print("Initial shape:", df.shape)
display(df.head())
print(df.dtypes)

Initial shape: (1, 17)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude
0,1,"[datetime.date(2006, 3, 24), datetime.date(200...","['Falcon 1', 'Falcon 1', 'Falcon 1', 'Falcon 1...",[[ 20. ]\n [ 5919.16534091]\n [ 165....,"['LEO', 'LEO', 'LEO', 'LEO', 'LEO', 'LEO', 'IS...","['Kwajalein Atoll', 'Kwajalein Atoll', 'Kwajal...","['None None', 'None None', 'None None', 'None ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal...","[None, None, None, None, None, None, None, Non...","[None, None, None, None, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","['Merlin1A', 'Merlin2A', 'Merlin2C', 'Merlin3C...","[167.7431292, 167.7431292, 167.7431292, 167.74...","[9.0477206, 9.0477206, 9.0477206, 9.0477206, 2..."

FlightNumber       int64
Date              object
BoosterVersion    object
PayloadMass       object
Orbit             object
LaunchSite        object
Outcome           object
Flights           object
GridFins          object
Reused            object
Legs              object
LandingPad        object
Block             object
ReusedCount       object
Serial            object
Longitude         object
Latitude          object
dtype: object

In [2]:
print("Missing values by column:")
display(df.isna().sum().sort_values(ascending=False).head(15))
print("Columns:", df.columns.tolist())

Missing values by column:

FlightNumber      0
Date              0
BoosterVersion    0
PayloadMass       0
Orbit             0
LaunchSite        0
Outcome           0
Flights           0
GridFins          0
Reused            0
Legs              0
LandingPad        0
Block             0
ReusedCount       0
Serial            0
dtype: int64

Columns: ['FlightNumber', 'Date', 'BoosterVersion', 'PayloadMass', 'Orbit', 'LaunchSite', 'Outcome', 'Flights', 'GridFins', 'Reused', 'Legs', 'LandingPad', 'Block', 'ReusedCount', 'Serial', 'Longitude', 'Latitude']

In [3]:
# Normalize common course column names if needed
df.columns = [c.strip() for c in df.columns]
if "PayloadMass" in df.columns:
    df["PayloadMass"] = pd.to_numeric(df["PayloadMass"], errors="coerce")
    df["PayloadMass"] = df["PayloadMass"].fillna(df["PayloadMass"].mean())

# Create binary landing success label from Outcome when available
if "Outcome" in df.columns:
    unsuccessful = {"Failure (drone ship)", "Failure (ground pad)", "No attempt", "No attempt"}
    df["Class"] = (~df["Outcome"].isin(unsuccessful)).astype(int)

print("After basic cleaning:", df.shape)
display(df.head())

After basic cleaning: (1, 18)

,FlightNumber,Date,BoosterVersion,PayloadMass,Orbit,LaunchSite,Outcome,Flights,GridFins,Reused,Legs,LandingPad,Block,ReusedCount,Serial,Longitude,Latitude,Class
0,1,"[datetime.date(2006, 3, 24), datetime.date(200...","['Falcon 1', 'Falcon 1', 'Falcon 1', 'Falcon 1...",NaN,"['LEO', 'LEO', 'LEO', 'LEO', 'LEO', 'LEO', 'IS...","['Kwajalein Atoll', 'Kwajalein Atoll', 'Kwajal...","['None None', 'None None', 'None None', 'None ...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal...","[False, False, False, False, False, False, Fal...","[None, None, None, None, None, None, None, Non...","[None, None, None, None, 1, 1, 1, 1, 1, 1, 1, ...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","['Merlin1A', 'Merlin2A', 'Merlin2C', 'Merlin3C...","[167.7431292, 167.7431292, 167.7431292, 167.74...","[9.0477206, 9.0477206, 9.0477206, 9.0477206, 2...",1

In [4]:
df.to_csv("dataset_part_2_cleaned.csv", index=False)
print("Saved dataset_part_2_cleaned.csv")

Saved dataset_part_2_cleaned.csv

## Interpretation
Document missing values, the treatment applied, and the definition of the target class. Do not report a fixed number of missing values unless it matches the displayed output from your run.